/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmnode_free: (a: number, b: number) => void;
export const create_node: () => number;
export const export_node: (a: number) => [number, number];
export const generate_handshake_link: (a: number, b: number, c: number, d: number) => [number, number];
export const import_node: (a: number, b: number) => [number, number, number];
export const init_wasm: () => void;
export const load_node: (a: number, b: number, c: number, d: number) => [number, number, number];
export const parse_handshake_link: (a: number, b: number) => [number, number];
export const wasmnode_add_move: (a: number, b: number, c: number) => void;
export const wasmnode_add_peer: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const wasmnode_add_scroll: (a: number, b: number) => void;
export const wasmnode_add_tap: (a: number, b: number, c: number) => void;
export const wasmnode_chain_len: (a: number) => number;
export const wasmnode_chao_address: (a: number) => [number, number];
export const wasmnode_create_send: (a: number, b: number, c: number, d: number, e: number, f: bigint) => [number, number];
export const wasmnode_entropy_count: (a: number) => number;
export const wasmnode_export_chain: (a: number) => [number, number];
export const wasmnode_export_keystore: (a: number) => [number, number];
export const wasmnode_get_balance: (a: number) => bigint;
export const wasmnode_get_chain: (a: number, b: number, c: number) => [number, number];
export const wasmnode_get_entropy: (a: number) => [number, number];
export const wasmnode_get_peers: (a: number) => [number, number];
export const wasmnode_info: (a: number) => [number, number];
export const wasmnode_latest_block: (a: number) => [number, number];
export const wasmnode_node_id: (a: number) => [number, number];
export const wasmnode_public_key: (a: number) => [number, number];
export const wasmnode_receive_send: (a: number, b: number, c: number) => [number, number];
export const wasmnode_try_mine: (a: number) => [number, number];
export const wasmnode_verify_block: (a: number, b: number, c: number) => number;
export const wasmnode_new: () => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
